//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malware.MDKUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Malware.MDKUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the blueprint {0}?.
        /// </summary>
        internal static string BlueprintManagerDialog_OnDeletingBlueprint_Description {
            get {
                return ResourceManager.GetString("BlueprintManagerDialog_OnDeletingBlueprint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Blueprint.
        /// </summary>
        internal static string BlueprintManagerDialog_OnDeletingBlueprint_Title {
            get {
                return ResourceManager.GetString("BlueprintManagerDialog_OnDeletingBlueprint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string BlueprintManagerDialogModel_CopyToClipboard_Copy {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_CopyToClipboard_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The blueprint was copied to the clipboard..
        /// </summary>
        internal static string BlueprintManagerDialogModel_CopyToClipboard_Copy_Description {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_CopyToClipboard_Copy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Copying Script.
        /// </summary>
        internal static string BlueprintManagerDialogModel_CopyToClipboard_Copy_Error {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_CopyToClipboard_Copy_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the attempt to copy the blueprint.
        ///
        ///{0}.
        /// </summary>
        internal static string BlueprintManagerDialogModel_CopyToClipboard_Copy_Error_Description {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_CopyToClipboard_Copy_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Deleting Blueprint.
        /// </summary>
        internal static string BlueprintManagerDialogModel_Delete_Error {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_Delete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the attempt to delete the blueprint.
        ///
        ///{0}.
        /// </summary>
        internal static string BlueprintManagerDialogModel_Delete_Error_Description {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_Delete_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t Delete Blueprint.
        /// </summary>
        internal static string BlueprintModel_Delete_Error {
            get {
                return ResourceManager.GetString("BlueprintModel_Delete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The blueprint {0} could not be deleted:
        ///
        ///{1}.
        /// </summary>
        internal static string BlueprintModel_Error_Description {
            get {
                return ResourceManager.GetString("BlueprintModel_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty or contain any of the following characters: {0}.
        /// </summary>
        internal static string BlueprintModel_GetErrors_InvalidName {
            get {
                return ResourceManager.GetString("BlueprintModel_GetErrors_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game binaries are required to create and deploy an MDK project..
        /// </summary>
        internal static string NewScriptWizardDialogModel_GameBinPath_GameBinariesRequired {
            get {
                return ResourceManager.GetString("NewScriptWizardDialogModel_GameBinPath_GameBinariesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output path is required to create an MDK project..
        /// </summary>
        internal static string NewScriptWizardDialogModel_OutputPath_OutputPathRequired {
            get {
                return ResourceManager.GetString("NewScriptWizardDialogModel_OutputPath_OutputPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Failed.
        /// </summary>
        internal static string RequestUpgradeDialogModel_OnSave_Error {
            get {
                return ResourceManager.GetString("RequestUpgradeDialogModel_OnSave_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the attempt to upgrade the project(s)..
        /// </summary>
        internal static string RequestUpgradeDialogModel_OnSave_Error_Description {
            get {
                return ResourceManager.GetString("RequestUpgradeDialogModel_OnSave_Error_Description", resourceCulture);
            }
        }
    }
}
