//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malware.MDKDefaultModules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Malware.MDKDefaultModules.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating the combined script for {0}.
        /// </summary>
        internal static string DefaultComposer_CreateProgramDocument_Error {
            get {
                return ResourceManager.GetString("DefaultComposer_CreateProgramDocument_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating script for {0}.
        /// </summary>
        internal static string DefaultComposer_GenerateScript_Error {
            get {
                return ResourceManager.GetString("DefaultComposer_GenerateScript_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading configuration for {0}.
        /// </summary>
        internal static string DefaultLoader_LoadProjectOptions_Error {
            get {
                return ResourceManager.GetString("DefaultLoader_LoadProjectOptions_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading script projects from {0}.
        /// </summary>
        internal static string DefaultLoader_LoadScriptProjects_Error {
            get {
                return ResourceManager.GetString("DefaultLoader_LoadScriptProjects_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing final script for {0}.
        /// </summary>
        internal static string DefaultPublisher_PublishAsync_Error {
            get {
                return ResourceManager.GetString("DefaultPublisher_PublishAsync_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDK was not allowed to write the final script for {0}: Unauthorized access.
        /// </summary>
        internal static string DefaultPublisher_PublishAsync_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("DefaultPublisher_PublishAsync_UnauthorizedAccess", resourceCulture);
            }
        }
    }
}
